-- Generated by nwg-displays on 2026-09-29 at 19:35:33. Do not edit manually.

hl.monitor({
    output = "eDP-1", -- inbuilt
    mode = "1920x1080@60.05",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1", -- HDMI port
    mode = "1920x1080@60.03",
    position = "1920x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
    vrr = 1
})
hl.monitor({
    output = "DP-1", -- HDMI via dock/usb hub
    mode = "1920x1080@60.03",
    position = "1920x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
    vrr = 1
})