-- Generated by nwg-displays on 2026-08-26 at 19:15:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "0x0",
    scale = 0.9999999999999997
})
